---
title: "exe3_lab3_bayesian learning"
author: "zahra jalilpour"
date: '2021-06-05'
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
library(rstan)
library(ggplot2)

knitr::opts_chunk$set(echo = TRUE)
```

# 3

## a

```{r}
T<-200
mu<- 20
sigma_sq<- 4
AR_process <- function(mu, phi,  T,sigma_sq){
  x<- rep(0, T)
  x[1]<- mu
  
  for (t in 1:(T-1)){
    x[t+1] <- mu + phi * (x[t] - mu) + rnorm(1, mean=0, sd=sqrt(sigma_sq))
  } 

return(x)
}
simulation_AR <- function(mu, phi,  T,sigma_sq ){
  sim <- AR_process(mu, phi,  T,sigma_sq)
  AR_df <- data.frame(x=1:T, y=sim)
  AR_plot <- ggplot(AR_df)+
    geom_line(aes(x=x, y=y), color= "#2E4053")+
    labs(title= paste("Simulation of AR process for phi= ",phi), x="iteration", y="mu",color="legend")+
    theme_light()
  
  return(AR_plot)
}

plot1 <- simulation_AR(mu= 10, phi=-0.7, T=200, sigma_sq=2)
plot2 <- simulation_AR(mu= 10, phi=-0.2, T=200, sigma_sq=2)
plot3 <- simulation_AR(mu= 10, phi=0.8, T=200, sigma_sq=2)
plot4 <- simulation_AR(mu= 10, phi=1, T=200, sigma_sq=2)
par(mfrow=c(3,3))
plot1
plot2
plot3
plot4
```

## b
```{r}
T<-200
mu<- 20
sigma_sq<- 4
AR_process <- function(mu, phi,  T,sigma_sq){
  x<- rep(0, T)
  x[1]<- mu
  
  for (t in 1:(T-1)){
    x[t+1] <- mu + phi * (x[t] - mu) + rnorm(1, mean=0, sd=sqrt(sigma_sq))
  } 

return(x)
}



X = AR_process(mu = 20, T = 200, phi = 0.3, sigma_sq = 4)
Y = AR_process(mu = 20, T = 200, phi = 0.9, sigma_sq = 4)
# Defining Stan model

stanModel = '
data {
  int<lower=0> N;
  vector[N] y;
}
parameters {
  real mu;
  real phi;
  real<lower=0> sigma_sq;
}
model {
  mu~normal(0,100);
  sigma_sq ~ scaled_inv_chi_square(1,2);
  for (t in 2:N){
    y[t] ~ normal(mu+(y[t-1]-mu)*phi,sigma_sq);
  }
}'

stan_ModelX = stan(model_code = stanModel,
                  data = list(N = length(X), y = X),
                  warmup = 1000,
                  iter = 2000,chains=1)
stan_ModelY = stan(model_code = stanModel,
                  data = list(N = length(Y), y = Y),
                  warmup = 1000,
                  iter = 2000,chains=1)


# extract posterior sample
posterior_X = extract(stan_ModelX)
posterior_paramsX = As.mcmc.list(stan_ModelX)
posterior_Y = extract(stan_ModelY)
posterior_paramsY = As.mcmc.list(stan_ModelY)



new_df <- data.frame(mu_x=posterior_X$mu, phi_x=posterior_X$phi, mu_y=posterior_Y$mu, phi_y=posterior_Y$phi)
ggplot(new_df)+
  geom_point(aes(x=mu_x, y= phi_x),color="blue")+
  labs(title="joint posterior of mu and phi of process1", y="phi", x="mu", color="Legend")+
  theme_light()

ggplot(new_df)+
  geom_point(aes(x=mu_y, y= phi_y),color="blue")+
  labs(title="joint posterior of mu and phi of process2", y="phi", x="mu", color="Legend")+
  theme_light()


```

```{r}
stan_ModelX

pairs(stan_ModelX)

```

```{r}
stan_ModelY

pairs(stan_ModelY)
```


